//#region DEPARTMENT
export const LOAD_DEPARTMENT = 'LOAD_DEPARTMENT';
export const LOAD_DEPARTMENT_BY_ID = 'LOAD_DEPARTMENT_BY_ID';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
//#endregion

//#region POSITION_TYPE
//POSITION_TYPE
export const LOAD_POSITION_TYPE = 'LOAD_POSITION_TYPE';
export const FILTER_POSITION_TYPE = 'FILTER_POSITION_TYPE';
export const ADD_POSITION_TYPE = 'ADD_POSITION_TYPE';
export const UPDATE_POSITION_TYPE = 'UPDATE_POSITION_TYPE';
export const DELETE_POSITION_TYPE = 'DELETE_POSITION_TYPE';
export const SET_CURRENT_POSITION_TYPE = 'SET_CURRENT_POSITION_TYPE';
export const CLEAR_CURRENT_POSITION_TYPE = 'CLEAR_CURRENT_POSITION_TYPE';
//#endregion

//#region STAFF
export const LOAD_STAFF = 'LOAD_STAFF';
export const LOAD_STAFF_BY_ID = 'LOAD_STAFF_BY_ID';
export const ADD_STAFF = 'ADD_STAFF';
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';
export const SET_CURRENT_STAFF = 'SET_CURRENT_STAFF';
export const CLEAR_CURRENT_STAFF = 'CLEAR_CURRENT_STAFF';

//#endregion

//#region  STAFF_RELATIVE
export const LOAD_STAFF_RELATIVE = 'LOAD_STAFF_RELATIVE';
export const LOAD_STAFF_RELATIVE_BY_STAFF_ID = 'LOAD_STAFF_RELATIVE_BY_STAFF_ID';
export const FILTER_STAFF_RELATIVE = 'FILTER_STAFF_RELATIVE';
export const ADD_STAFF_RELATIVE = 'ADD_STAFF_RELATIVE';
export const ADD_STAFF_RELATIVE_BY_STAFF_ID = 'ADD_STAFF_RELATIVE_BY_STAFF_ID';
export const UPDATE_STAFF_RELATIVE = 'UPDATE_STAFF_RELATIVE';
export const UPDATE_STAFF_RELATIVE_BY_STAFF_ID = 'UPDATE_STAFF_RELATIVE_BY_STAFF_ID';
export const DELETE_STAFF_RELATIVE = 'DELETE_STAFF_RELATIVE';
export const DELETE_STAFF_RELATIVE_BY_STAFF_ID = 'DELETE_STAFF_RELATIVE_BY_STAFF_ID';
export const SET_CURRENT_STAFF_RELATIVE = 'SET_CURRENT_STAFF_RELATIVE';
export const CLEAR_CURRENT_STAFF_RELATIVE = 'CLEAR_CURRENT_STAFF_RELATIVE';

//#endregion 

//#region STAFF_EXP
export const LOAD_STAFF_EXPERIENCE = 'LOAD_STAFF_EXPERIENCE';
export const LOAD_STAFF_EXPERIENCE_BY_ID = 'LOAD_STAFF_EXPERIENCE_BY_ID';
export const ADD_STAFF_EXPERIENCE = 'ADD_STAFF_EXPERIENCE';
export const UPDATE_STAFF_EXPERIENCE = 'UPDATE_STAFF_EXPERIENCE';
export const DELETE_STAFF_EXPERIENCE = 'DELETE_STAFF_EXPERIENCE';
export const FILTER_STAFF_EXPERIENCE = 'FILTER_STAFF_EXPERIENCE';
export const CLEAR_FILTER_STAFF_EXPERIENCE = 'CLEAR_FILTER_STAFF_EXPERIENCE';
//#endregion
//#region STAFF_AGREEMENT
export const LOAD_STAFF_AGREEMENT = 'LOAD_STAFF_AGREEMENT';
export const ADD_STAFF_AGREEMENT = 'ADD_STAFF_AGREEMENT';
export const FILTER_STAFF_AGREEMENT = 'FILTER_STAFF_AGREEMENT';
export const CLEAR_FILTER_STAFF_AGREEMENT = 'CLEAR_FILTER_STAFF_AGREEMENT';
//#endregion

//#region 

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
//#endregion

//#region GLOBAL
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const ERROR = 'ERROR';
export const DO_COMBO_BOX = 'DO_COMBO_BOX';
export const LOAD_STATUS_TYPE = 'LOAD_STATUS_TYPE';
//#endregion